{% set name = "certbot-nginx" %}
{% set version = "1.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/certbot-nginx-{{ version }}.tar.gz
  sha256: e0a954d49461e3209173cade9c49e8abfdc697467d1ae312bb230a43f7c60959

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - acme >=1.4.0
    - certbot >=1.6.0
    - pyopenssl >=17.3.0
    - pyparsing >=2.2.0
    - python >=3.6
    - setuptools >=39.0.1
    - zope.interface

test:
  imports:
    - certbot_nginx
    - certbot_nginx._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: Nginx plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
